name: learning yaml
run-name: ${{ github.actor }} is learning to YAML
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
jobs:
  my_first_job:
    name: check bats version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install -g bats
    - run: bats -v
